# Generated by Django 5.0.4 on 2024-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_awards_earn_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='deployment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Deployment date'),
        ),
    ]
