# Generated by Django 5.0.4 on 2024-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitesettings_remove_user_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(max_length=100, verbose_name='End year'),
        ),
    ]
