# Generated by Django 5.0.4 on 2024-04-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_experience_end_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='award',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_offer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_experience',
        ),
    ]
