# Generated by Django 5.0.4 on 2024-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_user_award_remove_user_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='personal_image/', verbose_name='Profile picture'),
        ),
    ]
