# Generated by Django 5.0.4 on 2024-04-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('E-commerce website', 'E-commerce website'), ('Business website', 'Business website'), ('Media website', 'Media website'), ('Educational website', 'Educational website'), ('Membership website', 'Membership website'), ('Backend development', 'Backend development'), ('Architecture', 'Architecture'), ('Database design', 'Database design'), ('API development', 'API development')], max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='projects/images/main', verbose_name='Image')),
                ('about_project', models.TextField(max_length=200, verbose_name='About project')),
                ('deployment_year', models.DateField(verbose_name='Deployment year')),
                ('client', models.CharField(max_length=50, verbose_name='Client')),
                ('project_type', models.CharField(choices=[('Dynamic', 'Dynamic'), ('Static', 'Static')], max_length=100, verbose_name='Project type')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.services', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
