# Generated by Django 5.0.4 on 2024-04-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_services_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='services',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main'),
        ),
    ]
